version: '3.8'

services:
  frontend:
    build:
      context: ./tasks-manager
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase?schema=public
    depends_on:
      - rabbitmq
      - db

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - NODE_ENV=production
      - DIRECT_URL=postgresql://user:password@db:5432/mydatabase?schema=public
    depends_on:
      - frontend
      - rabbitmq
      - db
    volumes:
      - /app/node_modules

  rabbitmq:
    image: rabbitmq:4.1.1-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgres_data:
